### Get all
GET http://127.0.0.1:8080/users-service/users
Accept: application/json

### Get by ID
GET http://127.0.0.1:8080/users-service/users/550e8400-e29b-41d4-a716-446655440009
Accept: application/json

### Create
POST http://127.0.0.1:8080/users-service/users
Content-Type: application/json

{
  "email": "user10@example.com",
  "name": "User10",
  "surname": "Ten"
}

### Update
PUT http://127.0.0.1:8080/users-service/users/550e8400-e29b-41d4-a716-446655440009
Content-Type: application/json

{
  "email": "user99@example.com",
  "name": "User99",
  "surname": "Nine9"
}

### Delete
DELETE http://127.0.0.1:8080/users-service/users/9b1be0eb-6614-4521-96d3-a15d3e87f3d4
Content-Type: application/json
