spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    open-in-view: false
  sql:
    init:
      platform: postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka
  instance:
    preferIpAddress: true

logging:
  level:
    root: info
    sql: info
    web: info
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
  file:
    name: ./.local/logs/${spring.application.name}/${spring.application.name}-${server.port}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
