spring:
  application:
    name: discovery
server:
  port: 9090
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    # eureka client disabled, but ReplicationTaskProcessor generates exception
    service-url:
      defaultZone: http://localhost:9090/eureka/
